### ISSUE TITLE
Issue due to port in windows 10

### ISSUE THREAD

**Issue by ryan185** [IntelRealSense/RealSenseID#108]
Hi,

I am running files after building the python Wrapper in windows and getting error like this in almost all file

[2021-08-02 14:43:11.898] [error] [FaceAuthenticatorImpl] Failed to open serial port. GetLastError: 2
[2021-08-02 14:43:11.905] [debug] [NonSecureSession] Close session
Traceback (most recent call last):
  File "enroll_image.py", line 45, in <module>
    enroll_with_image(sys.argv[1], sys.argv[2])
  File "enroll_image.py", line 36, in enroll_with_image
    with rsid_py.FaceAuthenticator(PORT) as f:
RuntimeError: Error

**Comment by ryan185** [comment]
When running viewer.py it is showing camera feed but after pressing key "a", "e", "f" it is terminating
Version: 0.23.0
[2021-08-02 15:20:13.369] [debug] [Utilities] detected capture device.
[2021-08-02 15:20:13.471] [debug] [Preview] Preview started!
[2021-08-02 15:28:18.172] [debug] [WindowsSerial] Opening serial port COM9
[2021-08-02 15:28:18.173] [error] [FaceAuthenticatorImpl] Failed to open serial port. GetLastError: 2
[2021-08-02 15:28:18.174] [debug] [NonSecureSession] Close session
Traceback (most recent call last):
  File "viewer.py", line 238, in <module>
    main()
  File "viewer.py", line 234, in main
    input_loop()
  File "viewer.py", line 127, in input_loop
    cmd_exec.get(chr(keycode), lambda: None)()
  File "viewer.py", line 83, in auth_example
    with rsid_py.FaceAuthenticator(PORT) as f:
RuntimeError: Error
