### ISSUE TITLE
Error in RealSenseId f455 Android app(version v0.18.1)

### ISSUE THREAD

**Issue by revathi1995** [IntelRealSense/RealSenseID#109]
I have run the RealSenseId android example code at the time appear the following error. 

----------------------------------------------------------------------------------------------------

| Required Info                         |                                     |
|-------------------------------- |------------------------- |
| Camera Model                       | { f455 }                         | 
| Firmware Version                   | (F450_2.8.0.7_SIGNED) | 
| Operating System & Version |   {Win (10)}                   | 
| Platform                                 | PC                                |
| SDK Version                           |  {v0.18.1 }                     | 
| Language                               |  {java}                           | 

### Issue Description
2021-07-19 18:54:38.009 8456-8456/com.intel.realsenseid.f450androidexample E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.intel.realsenseid.f450androidexample, PID: 8456
java.lang.UnsatisfiedLinkError: dlopen failed: library "libRealSenseIDSwigJNI.so" not found
at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
at java.lang.System.loadLibrary(System.java:1664)
at com.intel.realsenseid.f450androidexample.MainActivity.onCreate(MainActivity.java:113)
at android.app.Activity.performCreate(Activity.java:8000)
at android.app.Activity.performCreate(Activity.java:7984)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7656)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947).

how to solve this problem?. Please guide us.

**Comment by Gilaadb** [comment]
Hi.
If you are using the source code from Github, then while compiling the Android example, libRealSenseIDSwigJNI.so should be built automatically. If you are using the SDK, then you have it prebuilt in release (for both secured and unsecured flavors).
Can you describe the exact steps you took to build and install it to the device?
